final Map<String, List<String>> markaModelMap = {
  "Audi": ["A3 e-tron", "e-tron", "e-tron GT", "Q4 e-tron"],
  "BMW": ["i3", "i4", "iX"],
  "BYD": ["Atto 3", "Tang EV", "Han EV", "Seal"],
  "Chevrolet": ["Bolt EV", "Bolt EUV"],
  "Chrysler": ["Pacifica Hybrid"],
  "Fisker": ["Ocean"],
  "Ford": ["Mustang Mach-E", "F-150 Lightning", "E-Transit"],
  "Genesis": ["GV60"],
  "Hyundai": ["Kona Electric", "Ioniq 5", "Ioniq 6"],
  "Jaguar": ["I-PACE"],
  "Kia": ["Soul EV", "Niro EV", "EV6"],
  "Lucid": ["Air"],
  "Mercedes": ["EQA", "EQB", "EQC", "EQS"],
  "Nissan": ["Leaf", "Ariya"],
  "Polestar": ["Polestar 1", "Polestar 2"],
  "Rivian": ["R1T", "R1S"],
  "Tesla": ["Model 3", "Model S", "Model X", "Model Y"],
  "Toyota": ["bZ4X"],
  "Volkswagen": ["ID.3", "ID.4", "ID.5", "ID.6"],
};
