// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsxBAgUVoFZG4pnee3fNd2DhjGk659FlE',
    appId: '1:383559891186:web:459d119d0d90e75faef86b',
    messagingSenderId: '383559891186',
    projectId: 'evrylogins',
    authDomain: 'evrylogins.firebaseapp.com',
    storageBucket: 'evrylogins.appspot.com',
    measurementId: 'G-53FLNMGPRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxSPwjcaX-kr8TZQ-Xh0-np1SJmKEvwVw',
    appId: '1:383559891186:android:4c0008502c49669eaef86b',
    messagingSenderId: '383559891186',
    projectId: 'evrylogins',
    storageBucket: 'evrylogins.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3JxsFd0YAlW3R89tXRZTw2tP6-l427e4',
    appId: '1:383559891186:ios:9bac0eeeebd9c991aef86b',
    messagingSenderId: '383559891186',
    projectId: 'evrylogins',
    storageBucket: 'evrylogins.appspot.com',
    iosBundleId: 'com.example.evryApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3JxsFd0YAlW3R89tXRZTw2tP6-l427e4',
    appId: '1:383559891186:ios:9bac0eeeebd9c991aef86b',
    messagingSenderId: '383559891186',
    projectId: 'evrylogins',
    storageBucket: 'evrylogins.appspot.com',
    iosBundleId: 'com.example.evryApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsxBAgUVoFZG4pnee3fNd2DhjGk659FlE',
    appId: '1:383559891186:web:823db2a95e2707f5aef86b',
    messagingSenderId: '383559891186',
    projectId: 'evrylogins',
    authDomain: 'evrylogins.firebaseapp.com',
    storageBucket: 'evrylogins.appspot.com',
    measurementId: 'G-6162M4WRVN',
  );
}
